### ISSUE TITLE
0.4.8.4 on Hackage is missing Common.h and BitGetTest.hs

### ISSUE THREAD

**Issue by erictapen** [idontgetoutmuch/binary-low-level#12]
I guess 4c340d1191b78c2dfe9c0cabe46fb266077563de introduced this. These files are missing, that are necessary for the package to build on Nixpkgs:

```
./src/Data/Binary/Strict/Common.h
./tests/BitGetTest.hs
```

Would it be possible to get a new release on hackage with these files included?

**Comment by idontgetoutmuch** [comment]
Should be fixed - I added a test stanza as well

**Comment by erictapen** [comment]
Great, thank you.
