### ISSUE TITLE
Reading signed integers with BitGet

### ISSUE THREAD

**Issue by dmcclean** [idontgetoutmuch/binary-low-level#3]
Would you be interested in a patch to allow reading of signed `Int16`, `Int32`, etc types in the `BitGet` monad with functions like `getAsInt16` alongside the unsigned `getAsWord16` (etc) functions that are already there?

The `Data.Word` documentation says: 

> Coercing word types to and from integer types preserves representation, not sign.

so these would need to perform sign extension prior to the cast.

I am writing a parser for a binary format that makes extensive use of small signed fields, for example signed 28 bit longitudes and 27 bit latitudes.

**Comment by idontgetoutmuch** [comment]
Sounds interesting - I am happy to accept a patch - thanks for making contact.

**Comment by idontgetoutmuch** [comment]
Sorry for taking so long
