### ISSUE TITLE
Missing Imports?

### ISSUE THREAD

**Issue by liu3tao** [idontgetoutmuch/binary-low-level#4]
I want to use binary-strict in my project to parse captured frames in binary. However, building binary-strict failed with the following message:

```
Building binary-strict-0.4.8.3...
Preprocessing library binary-strict-0.4.8.3...

src/Data/Binary/Strict/BitGet.hs:2:16: Warning:
    -fglasgow-exts is deprecated: Use individual extensions instead

src/Data/Binary/Strict/Get.hs:2:16: Warning:
    -fglasgow-exts is deprecated: Use individual extensions instead

src/Data/Binary/Strict/IncrementalGet.hs:2:16: Warning:
    -fglasgow-exts is deprecated: Use individual extensions instead
[1 of 9] Compiling Data.Binary.Strict.Util ( src/Data/Binary/Strict/Util.hs, dist/build/Data/Binary/Strict/Util.o )
[2 of 9] Compiling Data.Binary.Strict.Class ( src/Data/Binary/Strict/Class.hs, dist/build/Data/Binary/Strict/Class.o )
[3 of 9] Compiling Data.Binary.Strict.IncrementalGet ( src/Data/Binary/Strict/IncrementalGet.hs, dist/build/Data/Binary/Strict/IncrementalGet.o )

src/Data/Binary/Strict/IncrementalGet.hs:104:10: Warning:
    Ignoring unusable UNPACK pragma on the first argument of `S'
    In the definition of data constructor `S'
    In the data declaration for `S'

src/Data/Binary/Strict/IncrementalGet.hs:104:10: Warning:
    Ignoring unusable UNPACK pragma on the third argument of `S'
    In the definition of data constructor `S'
    In the data declaration for `S'
[4 of 9] Compiling Data.Binary.Strict.Get ( src/Data/Binary/Strict/Get.hs, dist/build/Data/Binary/Strict/Get.o )
[5 of 9] Compiling Data.Binary.Strict.BitUtil ( src/Data/Binary/Strict/BitUtil.hs, dist/build/Data/Binary/Strict/BitUtil.o )
[6 of 9] Compiling Data.Binary.Strict.BitGet ( src/Data/Binary/Strict/BitGet.hs, dist/build/Data/Binary/Strict/BitGet.o )

src/Data/Binary/Strict/BitGet.hs:84:10:
    Not in scope: type constructor or class `Applicative'
```

After some inspection, it seems the problem is that
1. src/Data/Binary/Strict/BitGet.hs does not import Control.Applicative and Control.Moand, and
2. src/Data/Binary/BitPut.hs also does not import Control.Applicative.

I am able to build and install the binary-strict package after adding these imports. I am using GHC version 7.6.3, which is installed from haskell-platform package in Linux Mint 17.1.

Is is problem due to misconfiguration in my side, or would you consider including the fix? As a novice, I too apologize if the question is obvious, or off-base, or should be reported in a different manner.

Best,
Tao

**Comment by idontgetoutmuch** [comment]
There was a change in ghc which means these imports are no longer needed. You are very welcome to submit a patch which does conditional compilation so that the package installs under 7.6, 7.8 and 7.10. There are lots of examples in Hackage but be warned it's a bit of pain to get right. I can test 7.10 for you and I guess you can test 7.6. I'd recommend not testing on 7.8 unless you have a version of 7.8 handy. If someone needs it on 7.8 we can ask them to submit a patch.

**Comment by hvr** [comment]
fyi, I added a lower bound so that `cabal install binary-strict` can backtrack to binary-strict-0.4.8.2 on older GHCs, see https://hackage.haskell.org/package/binary-strict-0.4.8.3/revisions/ and http://matrix.hackage.haskell.org/package/binary-strict

**Comment by idontgetoutmuch** [comment]
I am closing as the new version does not have this problem.
